object Dependencies {
    const val coreKtx = "androidx.core:core-ktx:${Versions.CORE_KTX}"
    const val appCompat = "androidx.appcompat:appcompat:${Versions.APP_COMPAT}"
    const val fragment = "androidx.fragment:fragment-ktx:${Versions.FRAGMENT}"
    const val constraint = "androidx.constraintlayout:constraintlayout:${Versions.CONSTRAINT}"
    const val material = "com.google.android.material:material:${Versions.MATERIAL}"
    const val coil = "io.coil-kt:coil:${Versions.COIL}"
    const val dagger = "com.google.dagger:dagger:${Versions.DAGGER}"
    const val daggerCompiler = "com.google.dagger:dagger-compiler:${Versions.DAGGER}"
    const val coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.COROUTINES}"
    const val runtime = "androidx.lifecycle:lifecycle-runtime-ktx:${Versions.LIFECYCLE}"
    const val viewModel = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.LIFECYCLE}"
    const val okHttp3 = "com.squareup.okhttp3:okhttp:${Versions.OKHTTP3}"
    const val logging = "com.squareup.okhttp3:logging-interceptor:${Versions.OKHTTP3}"
    const val timber = "com.jakewharton.timber:timber:${Versions.TIMBER}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.RETROFIT}"
    const val serializationJson = "org.jetbrains.kotlinx:kotlinx-serialization-json:${Versions.SERIALIZATION_JSON}"
    const val serializationConverter = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:${Versions.SERIALIZATION_CONVERTER}"
}