object Dependencies {
    const val coreKtx = "androidx.core:core-ktx:${Versions.CORE_KTX}"
    const val appCompat = "androidx.appcompat:appcompat:${Versions.APP_COMPAT}"
    const val fragment = "androidx.fragment:fragment-ktx:${Versions.FRAGMENT}"
    const val constraint = "androidx.constraintlayout:constraintlayout:${Versions.CONSTRAINT}"
    const val material = "com.google.android.material:material:${Versions.MATERIAL}"
    const val coil = "io.coil-kt:coil:${Versions.COIL}"
    const val dagger = "com.google.dagger:dagger:${Versions.DAGGER}"
    const val daggerCompiler = "com.google.dagger:dagger-compiler:${Versions.DAGGER}"
    const val modo = "com.github.terrakok:modo:${Versions.MODO}"
    const val modoRender = "com.github.terrakok:modo-render-android-fm:${Versions.MODO}"
    const val coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.COROUTINES}"
    const val lifeCycleRuntime = "androidx.lifecycle:lifecycle-runtime-ktx:${Versions.LIFECYCLE}"
    const val lifecycleViewModel = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.LIFECYCLE}"
    const val lifecycleExt = "androidx.lifecycle:lifecycle-extensions:${Versions.LIFECYCLE}"
    const val lifecycleCommon = "androidx.lifecycle:lifecycle-common-java8:${Versions.LIFECYCLE}"
    const val viewBindingPropertyDelegate = "com.github.kirich1409:viewbindingpropertydelegate:1.4.7"
    const val okHttp3 = "com.squareup.okhttp3:okhttp:${Versions.OKHTTP3}"
    const val logging = "com.squareup.okhttp3:logging-interceptor:${Versions.OKHTTP3}"
    const val timber = "com.jakewharton.timber:timber:${Versions.TIMBER}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.RETROFIT}"
    const val serializationJson = "org.jetbrains.kotlinx:kotlinx-serialization-json:${Versions.SERIALIZATION_JSON}"
    const val serializationConverter = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:${Versions.SERIALIZATION_CONVERTER}"

    const val coroutinesTest = "org.jetbrains.kotlinx:kotlinx-coroutines-test:${Versions.COROUTINES_TEST}"
    const val kaspresso = "com.kaspersky.android-components:kaspresso:${Versions.KASPRESSO}"
    const val mockitoKotlin = "org.mockito.kotlin:mockito-kotlin:${Versions.MOCKITO}"
}


